epambrest/capacity

Teams.Security/UserDetails.cs
=> Fix-UserDetails

Teams.Tests/ManageTeamsServiceTest.cs, src/Teams/Controllers/ManageTeamsController.cs, src/Teams/Services/IManageTeamsService.cs, src/Teams/Services/ManageTeamsService.cs
1. Created "Get(team_id)" for logged in account in ManageTeamsController and ManageTeamsService
2. Covered by tests
=> 2.7 implement get by id team feature

Teams.Tests/ManageTeamsServiceTest.cs, src/Teams/Controllers/ManageTeamsController.cs, src/Teams/Services/IManageTeamsService.cs, src/Teams/Services/ManageTeamsService.cs
1. Implemented EditTeamName(team_id, team_name) in ManageTeamsController and ManageTeamsService
2. Covered by tests
=> 2.8 Implement edit team feature

Teams.Tests/ManageTeamsMembersServiceTest.cs, src/Teams/Controllers/ManageTeamMembersController.cs, src/Teams/Models/DisplayOptions.cs, src/Teams/Models/SortDirection.cs, src/Teams/Services/IManageTeamsMembersService.cs, src/Teams/Services/ManageTeamsMembersService.cs
1. Created "Get all team members(team_id, DisplayOptions)" for logged in account in ManageTeamMembersController and ManageTeamMembersSerivce
2. Covered by tests
=> 2.9 Implement get list of team members feature

src/Teams/Services/ManageTeamsService.cs, src/Teams/Views/ManageTeams/GetMyTeams.cshtml
=> 3.1 View for list of teams

Teams.Tests/ManageTeamServiceTest.cs, src/Teams/Controllers/ManageTeamsController.cs, src/Teams/Views/ManageTeams/GetMyTeams.cshtml
=> 3.2 Implement remove team view

src/Teams/Controllers/ManageTeamsController.cs, src/Teams/Services/ManageTeamsService.cs, src/Teams/Views/ManageTeams/EditTeamName.cshtml, src/Teams/Views/ManageTeams/GetMyTeams.cshtml
Description
As a customer I want to have interface to edit team
Solution
1. Implement view for editing team
a. Default value in "input" should be selected team to edit
2. Add Edit button to view for list of team
a. Should be shown only for owner of team
3. Find Edit icon, discuss with team to add it
4. Set Edit icon to button in list as shown in template
=> 3.3 Implement edit view for team

Teams.Tests/SprintRepositoryTest.cs, src/Teams/Data/ApplicationDbContext.cs, src/Teams/Data/Migrations/20201020175414_Sprint.Designer.cs, src/Teams/Data/Migrations/20201020175414_Sprint.cs, src/Teams/Models/Sprint.cs, src/Teams/Repository/SprintRepository.cs
1) Create Sprint table
2) Add Sprint model
3) Add EF migrations
4) Implement repository for sprint DB
5) Covered by tests
=> 4.2 Implement sprint table

Teams.Tests/ManageSprintsServiceTest.cs, src/Teams/Controllers/ManageSprintsController.cs, src/Teams/Controllers/ManageTeamsController.cs, src/Teams/Services/IManageSprintsService.cs, src/Teams/Services/ManageSprintsService.cs, src/Teams/Startup.cs, src/Teams/Views/ManageSprints/AllSprints.cshtml, src/Teams/Views/ManageSprints/ErrorGetAllSprints.cshtml, src/Teams/Views/ManageTeams/GetMyTeams.cshtml
=> 4.3 Implement get all sprints

Teams.Tests/ManageSprintsServiceTest.cs, src/Teams/Controllers/ManageSprintsController.cs, src/Teams/Services/IManageSprintsService.cs, src/Teams/Services/ManageSprintsService.cs, src/Teams/Views/ManageSprints/AllSprints.cshtml, src/Teams/Views/ManageSprints/GetSprintById.cshtml
=> 4.4 Implement get by id sprint feature

Teams.Tests/ManageSprintsServiceTest.cs, src/Teams/Controllers/ManageSprintsController.cs, src/Teams/Models/CombinedModel.cs, src/Teams/Models/Sprint.cs, src/Teams/Resources/Controllers.ManageSprintsController.en.resx, src/Teams/Resources/Controllers.ManageSprintsController.ru.resx, src/Teams/Services/IManageSprintsService.cs, src/Teams/Services/ManageSprintsService.cs, src/Teams/Startup.cs, src/Teams/Views/ManageSprints/AddError.cshtml, src/Teams/Views/ManageSprints/AddSprint.cshtml, src/Teams/Views/ManageSprints/AllSprints.cshtml, src/Teams/Views/ManageSprints/Error.cshtml
=> 4.7 implement view for adding sprint

Teams.Tests/ManageTasksServiceTest.cs, src/Teams/Controllers/ManageTasksController.cs, src/Teams/Services/IManageTasksService.cs, src/Teams/Services/ManageTasksService.cs, src/Teams/Startup.cs, src/Teams/Views/ManageTasks/ErrorGetTaskById.cshtml, src/Teams/Views/ManageTasks/GetTaskById.cshtml
=> 4.6 Implement get by id task feature

Teams.Tests/ManageSprintsServiceTest.cs, Teams.Tests/SprintRepositoryTest.cs, src/Teams/Controllers/ManageSprintsController.cs, src/Teams/Data/Migrations/20201020175414_Sprint.cs, src/Teams/Models/Sprint.cs, src/Teams/Repository/SprintRepository.cs, src/Teams/Resources/Controllers.ManageSprintsController.en.resx, src/Teams/Resources/Controllers.ManageSprintsController.ru.resx, src/Teams/Services/ManageSprintsService.cs, src/Teams/Views/ManageSprints/AddSprint.cshtml, src/Teams/Views/ManageSprints/AllSprints.cshtml, src/Teams/Views/ManageSprints/GetSprintById.cshtml
As a developer i dont want to see typo in our models.
When describing the model Sprint.An error was made in the property "StorePointInHours",
but right "StoryPointtInHours.
Find and fix all related typos related to this.
=> 4.13 Typo in model Sprint description 

Teams.Tests/ManageSprintsServiceTest.cs, src/Teams/Controllers/ManageSprintsController.cs, src/Teams/Services/IManageSprintsService.cs, src/Teams/Services/ManageSprintsService.cs, src/Teams/Views/ManageSprints/AllSprints.cshtml, src/Teams/Views/ManageSprints/ErrorRemove.cshtml
=> 4.9 Implement remove sprint feature and view

src/Teams/Controllers/ManageTasksController.cs, src/Teams/ViewModels/AllTasksForTeamViewModel.cs, src/Teams/Views/ManageTasks/AllTasksForTeam.cshtml
As a developer i do not want to receive a exception which is related to display AllTasksForTeam view (display team name).
If team doesn't have tasks you get exception. Because we take the team name from the first task.
To fix this bug, add a separate model for the view. Which will contain the list of tasks and the name of the team.
=> 4.14 If team doesn't have tasks you get exception

src/Teams/Controllers/ManageSprintsController.cs, src/Teams/Services/ManageSprintsService.cs, src/Teams/ViewModels/EditSprintViewModel.cs, src/Teams/Views/ManageSprints/EditSprint.cshtml
=> 5.5 feature have checkbox as mark

src/Teams/Controllers/ManageSprintsController.cs, src/Teams/Views/ManageSprints/AllSprints.cshtml
=> 5.4 Bug. Removal of sprint not working

src/Teams/Controllers/ManageTeamsController.cs, src/Teams/Views/ManageTeams/AddTeam.cshtml
=> 5.11 Bug. Redirect while add team don't work

src/Teams/Views/ManageSprints/AddSprint.cshtml
=> 5.5.1 Feature. Have checkbox as mark.

Tests/Teams.Business.Tests/ManageSprintsServiceTest.cs, Tests/Teams.Data.Tests/SprintRepositoryTest.cs, src/Teams.Data/Migrations/20201202135539_AddedStatusToSprint.Designer.cs, src/Teams.Data/Migrations/20201202135539_AddedStatusToSprint.cs, src/Teams.Data/Models/Sprint.cs, src/Teams.Data/Repository/SprintRepository.cs, src/Teams.Web/Controllers/ManageSprintsController.cs, src/Teams.Web/Resources/Controllers/ManageSprintsController.en.resx, src/Teams.Web/Resources/Controllers/ManageSprintsController.ru.resx, src/Teams.Web/ViewModels/EditSprintViewModel.cs, src/Teams.Web/ViewModels/SprintViewModel.cs, src/Teams.Web/Views/ManageSprints/AddSprint.cshtml, src/Teams.Web/Views/ManageSprints/AllSprints.cshtml, src/Teams.Web/Views/ManageSprints/EditSprint.cshtml, src/Teams.Web/Views/ManageSprints/GetSprintById.cshtml
I changed variable "IsActive" to variable "status" with integer type
=> added logic for status

src/Teams.Web/Controllers/ManageSprintsController.cs, src/Teams.Web/Controllers/ManageTasksController.cs, src/Teams.Web/Controllers/ManageTeamMembersController.cs, src/Teams.Web/Controllers/ManageTeamsController.cs, src/Teams.Web/Resources/Controllers/ManageSprintsController.ru.resx, src/Teams.Web/Resources/Controllers/ManageTasksController.en.resx, src/Teams.Web/Resources/Controllers/ManageTasksController.ru.resx, src/Teams.Web/Resources/Controllers/ManageTeamMembersController.en.resx, src/Teams.Web/Resources/Controllers/ManageTeamMembersController.ru.resx, src/Teams.Web/Resources/Controllers/ManageTeamsController.en.resx, src/Teams.Web/Resources/Controllers/ManageTeamsController.ru.resx, src/Teams.Web/Views/ManageSprints/NotOwnerError.cshtml, src/Teams.Web/Views/ManageTasks/NotOwnerError.cshtml, src/Teams.Web/Views/ManageTeamMembers/AddError.cshtml, src/Teams.Web/Views/ManageTeams/NameError.cshtml
=> 5.2 Bug. Show correct error message what is going wrong

.github/workflows/autotests.yml
I have added action for automatically build and test branch. I used new github's feature wich called "Actions". This is very useful feature which allows do automatically many things. I tested this solution in my forked repository with manual method. You can see result in attached screenshots. If you noticed some wrong things please write down.
Please read about this feature on these sites:
1) https://www.freecodecamp.org/news/what-are-github-actions-and-how-can-you-automate-tests-and-slack-notifications/
2) https://dev.to/kurtmkurtm/testing-net-core-apps-with-github-actions-3i76
3) https://rajbos.github.io/blog/2019/10/26/Deploy-dotnetcore-webapp-with-GitHub-Actions
4) official documentation: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actio …
=> 6.12 Improvement. Setup to build branches and run tests automatically in github

CODEOWNERS
I'm sorry. I forgot to add @SherbaKirill as default reviewer
=> 6.13 Improvement. Add default reviewers fix

src/Teams.Web/Controllers/ManageSprintsController.cs, src/Teams.Web/Views/ManageSprints/AddSprint.cshtml, src/Teams.Web/Views/ManageSprints/EditSprint.cshtml, src/Teams.Web/Views/ManageSprints/GetSprintById.cshtml, src/Teams.Web/Views/ManageTasks/AllTasksForTeam.cshtml, src/Teams.Web/Views/ManageTasks/GetResultTeamMember.cshtml
Someone accidentally erased all statuses logic in controller when was fixing conflicts, so i returned it. Also i fixed links (they weren't work).
=> Path-Fix: Statuses fix

src/Teams.Web/Controllers/ManageTasksController.cs, src/Teams.Web/ViewModels/Task/TaskFormViewModel.cs, src/Teams.Web/Views/ManageTasks/EditTask.cshtml
I've fixed bug with select in EditTask View which @desenzo mentioned
=> Fix select in EditTaskView

src/Teams.Web/Controllers/ManageTasksController.cs, src/Teams.Web/Resources/Views/ManageTasks/GetResultTeamMember.en.resx, src/Teams.Web/Resources/Views/ManageTasks/GetResultTeamMember.ru.resx, src/Teams.Web/ViewModels/Task/ResultsTasksForMemberViewModel.cs, src/Teams.Web/Views/ManageTasks/GetResultTeamMember.cshtml
See this pull request and leave your review please.
Before
After
=> Update result page to show correct result up

.github/workflows/pushDockerToACR.yml
I've created action to push our docker image to Azure Container Regestry. This action will work after 20-th Febrary, because our server isn't working now. If you noticed something wrong, please write down, also don't merge this pull request yet
=> 6.10 Improvement. Deploy application to server

src/Teams.Web/appsettings.json
=> Set release version 1.0.5

src/Teams.Web/appsettings.json
=> Set release version 1.0.9

src/Teams.Web/appsettings.json
=> Set release version 1.0.11

src/Teams.Web/appsettings.json
=> Set release version 1.0.13

src/Teams.Web/appsettings.json
=> Set release version 1.0.15

src/Teams.Business/Services/IManageSprintsService.cs, src/Teams.Business/Services/ManageSprintsService.cs, src/Teams.Web/Controllers/ManageSprintsController.cs, src/Teams.Web/Resources/Views/ManageSprints/GetSprintById.en.resx, src/Teams.Web/Resources/Views/ManageSprints/GetSprintById.ru.resx, src/Teams.Web/ViewModels/Sprint/SprintViewModel.cs, src/Teams.Web/Views/ManageSprints/GetSprintById.cshtml
Add total count of SP in sprint to View
Add average count of Sp in completed sprint to View
=> 6.9 Add total story points suggestion

src/Teams.Web/appsettings.json
=> Set release version 1.0.17

src/Teams.Web/appsettings.json
=> Set release version 1.0.20

src/Teams.Web/appsettings.json
=> Set release version 1.0.22

Tests/Teams.Business.Tests/ManageSprintsServiceTest.cs, Tests/Teams.Business.Tests/ManageTasksServiceTest.cs, Tests/Teams.Business.Tests/ManageTeamsServiceTest.cs, src/Teams.Business/Services/ManageSprintsService.cs, src/Teams.Business/Services/ManageTasksService.cs, src/Teams.Business/Services/ManageTeamsService.cs
=> 7.2 Incorect task/sprint/team name validation

src/Teams.Web/appsettings.json
=> Set release version 1.0.24

src/Teams.Data/Repository/TaskRepository.cs, src/Teams.Web/Controllers/ManageSprintsController.cs, src/Teams.Web/Resources/Views/ManageSprints/AddSprint.en.resx, src/Teams.Web/Resources/Views/ManageSprints/AddSprint.ru.resx, src/Teams.Web/Teams.Web.csproj, src/Teams.Web/ViewModels/Sprint/SprintViewModel.cs, src/Teams.Web/Views/ManageSprints/AddSprint.cshtml, src/Teams.Web/Views/Shared/_Layout.cshtml
In this task i made select menu when you create sprint you can select task from backlog. You can select multiple tasks
=> 7.3 Add tasks edit grid when creating spring

src/Teams.Web/appsettings.json
=> Set release version 1.0.26

src/Teams.Web/appsettings.json
=> Set release version 1.0.28

src/Teams.Web/Views/ManageMemberWorkingDays/_WorkingDaysPartial.cshtml, src/Teams.Web/Views/ManageSprints/AllSprints.cshtml
I've fixed two little bugs (bug with submit, problems with edit buttons and add buttons)
=> 7.8 Submit is not defined in browser console (all sprints tab)

src/Teams.Web/ViewModels/Sprint/SprintViewModel.cs
in this task i change attribute range in prop DaysInSprint
=> 7.7 Change range DaysInSprint 

src/Teams.Web/appsettings.json
=> Set release version 1.0.30

src/Teams.Web/appsettings.json
=> Set release version 1.0.31

src/Teams.Web/Areas/Identity/IdentityHostingStartup.cs, src/Teams.Web/Areas/Identity/Pages/Account/Manage/Email.cshtml, src/Teams.Web/Areas/Identity/Pages/Account/Manage/Email.cshtml.cs, src/Teams.Web/Areas/Identity/Pages/Account/Manage/Index.cshtml, src/Teams.Web/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs, src/Teams.Web/Areas/Identity/Pages/Account/Manage/ManageNavPages.cs, src/Teams.Web/Areas/Identity/Pages/Account/Manage/_Layout.cshtml, src/Teams.Web/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml, src/Teams.Web/Areas/Identity/Pages/Account/Manage/_ViewImports.cshtml, src/Teams.Web/Areas/Identity/Pages/Account/_ViewImports.cshtml, src/Teams.Web/Areas/Identity/Pages/_ValidationScriptsPartial.cshtml, src/Teams.Web/Areas/Identity/Pages/_ViewImports.cshtml
Added hidden views. Removed buttons for verify email, phone numbers and two-factor authorization.
Don't touched any logic.
=> 7.5 Remove verification account buttons

src/Teams.Web/appsettings.json
=> Set release version 1.0.34

src/Teams.Web/Controllers/ManageTasksController.cs, src/Teams.Web/Resources/Views/ManageTasks/AddTask.en.resx, src/Teams.Web/Resources/Views/ManageTasks/AddTask.ru.resx, src/Teams.Web/Resources/Views/ManageTasks/AddTaskIntoTeam.en.resx, src/Teams.Web/Resources/Views/ManageTasks/AddTaskIntoTeam.ru.resx, src/Teams.Web/Resources/Views/ManageTasks/EditTask.en.resx, src/Teams.Web/Resources/Views/ManageTasks/EditTask.ru.resx, src/Teams.Web/ViewModels/Task/TaskFormViewModel.cs, src/Teams.Web/ViewModels/Task/TaskViewModel.cs, src/Teams.Web/Views/ManageTasks/AddTask.cshtml, src/Teams.Web/Views/ManageTasks/AddTaskIntoTeam.cshtml, src/Teams.Web/Views/ManageTasks/EditTask.cshtml
Add checkbox in order to skip validation. If checkbox isn't checked user can add only github or bitbucket links. If checkbox is checked user can add any links.
=> 7.1 Add validation to Link of Task

src/Teams.Web/appsettings.json
=> Set release version 1.0.36

src/Teams.Web/Views/ManageMemberWorkingDays/_WorkingDaysPartial.cshtml
i increased timer of popup to 5 sec in workingdaysView. If you isn't agree with it, please write down. You can see result in video.
Link to video: https://drive.google.com/file/d/1ayK317-JgDfAjxM1JTYbsJpVL7AhjNJ5/view?usp=sharing
=> 7.12 Increase timer of popup

src/Teams.Web/appsettings.json
=> Set release version 1.0.38

src/Teams.Web/appsettings.json
=> Set release version 1.0.40

src/Teams.Web/appsettings.json
=> Set release version 1.0.41

src/Teams.Web/Controllers/ManageSprintsController.cs, src/Teams.Web/Controllers/ManageTasksController.cs, src/Teams.Web/Resources/Views/ManageTasks/AllTasksForTeam.ru.resx, src/Teams.Web/Resources/Views/ManageTasks/Shared/_NewLayout.en.resx, src/Teams.Web/Resources/Views/ManageTasks/Shared/_NewLayout.ru.resx, src/Teams.Web/Resources/Views/Shared/_LoginPartial.ru.resx, src/Teams.Web/ViewModels/Task/AllTasksForTeamViewModel.cs, src/Teams.Web/ViewModels/Task/TaskViewModel.cs, src/Teams.Web/Views/ManageSprints/AllSprints.cshtml, src/Teams.Web/Views/ManageTasks/AllTasksForTeam.cshtml, src/Teams.Web/Views/ManageTasks/Shared/_NewLayout.cshtml, src/Teams.Web/Views/Shared/_Layout.cshtml, src/Teams.Web/wwwroot/css/ManageTasks/AllTasksForTeam.css, src/Teams.Web/wwwroot/css/ManageTasks/Shared/_NewLayout.css
I added new layout for future "Views" (we'll duscus about it in meeting tommorow), also backlog page (AllTasksForTeamView) was updated. In the end i fixed a little bug in EditSprint (it was happening when TeamMember was null). You can see changes in video and screenshot. If you have comments and offers or i've done something wrong. Please write down. Update1: Please pay attention! some buttons doesn't do anything, handlers will added in next pull requests (as was required in issue 7.14).
Link to video: https://drive.google.com/file/d/1xgR1d2hMzlIyLeaVVTLa3UJGMcVW4_Zp/view?usp=sharing
=> 7.14 Update backlog page

src/Teams.Web/appsettings.json
=> Set release version 1.0.44

src/Teams.Web/appsettings.json
=> Set release version 1.0.46

README.md
I've updated our readme file. If you noticed some grammer or logical mistakes, please write down. You can see result on screenshoot.
=> 7.15 Create documentation.

src/Teams.Data/Models/Sprint.cs, src/Teams.Data/Models/Team.cs, src/Teams.Web/ViewModels/Sprint/EditSprintViewModel.cs, src/Teams.Web/ViewModels/Sprint/SprintViewModel.cs, src/Teams.Web/Views/ManageSprints/AllSprints.cshtml, src/Teams.Web/Views/ManageTeams/GetMyTeams.cshtml
=> 7.18 Problem with Layout. Problem with long names

src/Teams.Web/appsettings.json
=> Set release version 1.0.48

src/Teams.Web/appsettings.json
=> Set release version 1.0.49

src/Teams.Web/appsettings.json
=> Set release version 1.0.52

src/Teams.Web/appsettings.json
=> Set release version 1.0.53

src/Teams.Web/appsettings.json
=> Set release version 1.0.57

src/Teams.Web/appsettings.json
=> Set release version 1.0.61

src/Teams.Web/appsettings.json
=> Set release version 1.0.63

src/Teams.Web/appsettings.json
=> Set release version 1.0.65

src/Teams.Web/appsettings.json
=> Set release version 1.0.67
